package phelp

// This code was generated by mkparamfilefunc
// with parameters set at:
//	command line:5: -funcs personalOnly
//	command line:3: -group common.params-completion
//	command line:1: -private
//	command line:6: -verbose
//
// *** DO NOT EDIT ***
import (
	"path/filepath"

	"github.com/nickwells/filecheck.mod/filecheck"
	"github.com/nickwells/param.mod/v5/param"
	"github.com/nickwells/xdg.mod/xdg"
)

/*
setConfigFileForGroupCommonParamsCompletion adds a config file to the set which
the param parser will process before checking the command line parameters.
*/
func setConfigFileForGroupCommonParamsCompletion(ps *param.PSet) error {
	baseDir := xdg.ConfigHome()

	ps.AddGroupConfigFile("common.params-completion",
		filepath.Join(baseDir,
			"github.com",
			"nickwells",
			"param.mod",
			"v4",
			"param",
			"phelp",
			"group-common.params-completion.cfg"),
		filecheck.Optional)
	return nil
}
