package  param_test

// This code was generated by mkfunccontrolparamtype
// with parameters set at:
//	command line:5: -d This determines whether or not a ByName or ByPos param is expected to be set
//	command line:3: -for-testing
//	command line:2: -t ShouldBeSet
//	command line:7: -v ShouldNotBeSet
//	command line:9: -v ShouldBeSet
//
// *** DO NOT EDIT ***

// ShouldBeSetType This determines whether or not a ByName or ByPos param is expected to be set
// Generated Code
type ShouldBeSetType int

// Set the lower sentinel value to minus one so that the default (0)
// value is the first meaningful entry
const (
	MinValForShouldBeSetType ShouldBeSetType = iota - 1
	ShouldNotBeSet
	ShouldBeSet
	MaxValForShouldBeSetType
)

// IsValid is a method on the ShouldBeSetType type that can be used
// to check a received parameter for validity. It compares
// the value against the sentinel values for the type
// and returns false if it is outside the valid range
func (v ShouldBeSetType)IsValid() bool {
	if v <= MinValForShouldBeSetType {
		return false
	}
	if v >= MaxValForShouldBeSetType {
		return false
	}
	return true
}
